#ifndef __BSAL_SRV_HID_H__
#define __BSAL_SRV_HID_H__


#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <stdbool.h>
#include "bsal.h"



#define GATT_UUID_HID                              BSAL_GATT_SERVICE_HUMAN_INTERFACE_DEVICE
#define GATT_UUID_CHAR_PROTOCOL_MODE               BSAL_UUID_CHAR_PROTOCOL_MODE
#define GATT_UUID_CHAR_INPUT_REPORT                BSAL_UUID_CHAR_REPORT
#define GATT_UUID_CHAR_OUTPUT_REPORT               BSAL_UUID_CHAR_REPORT
#define GATT_UUID_CHAR_FEATURE_REPORT              BSAL_UUID_CHAR_REPORT
#define GATT_UUID_CHAR_REPORT_MAP                  BSAL_UUID_CHAR_REPORT_MAP
#define GATT_UUID_CHAR_BOOT_MOUSE_INPUT_REPORT     BSAL_UUID_CHAR_BOOT_MOUSE_INPUT_REPORT
#define GATT_UUID_CHAR_HID_INFORMATION             BSAL_UUID_CHAR_HID_INFORMATION
#define GATT_UUID_CHAR_HID_CONTROL_POINT           BSAL_UUID_CHAR_HID_CONTROL_POINT

#define GATT_UUID_BATTERY                          BSAL_GATT_SERVICE_BATTERY_SERVICE
#define GATT_UUID_CHAR_BAS_LEVEL                   BSAL_UUID_CHAR_BATTERY_LEVEL

#define GATT_UUID_DEVICE_INFORMATION               BSAL_GATT_SERVICE_DEVICE_INFORMATION
#define GATT_UUID_CHAR_MANUFACTURER_NAME_STRING    BSAL_UUID_CHAR_MANUFACTURER_NAME_STRING
#define GATT_UUID_CHAR_PNP_ID                      BSAL_UUID_CHAR_PNP_ID

#define GATT_UUID_GENERIC_ATTRIBUTE                BSAL_GATT_SERVICE_GENERIC_ATTRIBUTE

#define GATT_UUID_GENERIC_ACCESS                   BSAL_GATT_SERVICE_GENERIC_ACCESS
#define GATT_UUID_CHAR_DEVICE_NAME                 BSAL_UUID_CHAR_GAP_DEVICE_NAME
#define GATT_UUID_CHAR_GAP_APPEARANCE              BSAL_UUID_CHAR_GAP_APPEARANCE
#define GATT_UUID_CHAR_PPCP                        BSAL_UUID_CHAR_GAP_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS
#define GATT_UUID_CHAR_CENTRAL_ADDRESS_RESOLUTION  BSAL_UUID_CHAR_GAP_CENTRAL_ADDRESS_RESOLUTION


#define GATT_SVC_HID_REPORT_MAP_INDEX              35

void bsal_le_hid_svr_init(void *stack_ptr, void *app_callback);
#endif 


